
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form CDmain
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Music = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HOME = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        USER = new javax.swing.JLabel();
        MUSIC = new javax.swing.JLabel();
        Explore = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Personalize = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNICO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Music.png"))); // NOI18N
        Music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Music.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MusicMouseMoved(evt);
            }
        });
        Music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicMouseClicked(evt);
            }
        });
        jPanel1.add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Logout.png"))); // NOI18N
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutMouseMoved(evt);
            }
        });
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/User.png"))); // NOI18N
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UserMouseMoved(evt);
            }
        });
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Home.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 580));

        jPanel2.setBackground(new java.awt.Color(25, 24, 24));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HOME.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        HOME.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 20));

        LOGOUT.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 20));

        USER.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        USER.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 20));

        MUSIC.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MUSIC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(MUSIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));

        Explore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Explore.png"))); // NOI18N
        Explore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Explore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExploreMouseClicked(evt);
            }
        });
        jPanel2.add(Explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 130, 140));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel9.setText("EXPLORE");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        Personalize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/1494907775_icons_user.png"))); // NOI18N
        Personalize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Personalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonalizeMouseClicked(evt);
            }
        });
        jPanel2.add(Personalize, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel8.setText("PERSONALIZE");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 130, 20));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Ig.png"))); // NOI18N
        Background.setText("jLabel10");
        jPanel2.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -290, 1660, 1340));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 770, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    new Login().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        // TODO add your handling code here:
        HOME.setText("Home");
        
        
        
        
    }//GEN-LAST:event_HomeMouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
         HOME.setText("");
          LOGOUT.setText("");
           USER.setText("");
           MUSIC.setText("");
        
    }//GEN-LAST:event_jPanel1MouseMoved

    private void MusicMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseMoved
        // TODO add your handling code here:
        MUSIC.setText("Store");
    }//GEN-LAST:event_MusicMouseMoved

    private void UserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseMoved
        // TODO add your handling code here:
        USER.setText("Personalize");
    }//GEN-LAST:event_UserMouseMoved

    private void LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseMoved
        // TODO add your handling code here:
        LOGOUT.setText("Logout");
    }//GEN-LAST:event_LogoutMouseMoved

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        // TODO add your handling code here:
    
    }//GEN-LAST:event_HomeMouseEntered

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        // TODO add your handling code here:
        HOME.setText("");
    }//GEN-LAST:event_jPanel2MouseMoved

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
    new Home().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Personalize().setVisible(true);
    }//GEN-LAST:event_UserMouseClicked

    private void MusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_MusicMouseClicked

    private void ExploreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExploreMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_ExploreMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void PersonalizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalizeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
new Personalize().setVisible(true);
    }//GEN-LAST:event_PersonalizeMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
           this.setVisible(false);
new Personalize().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Explore;
    private javax.swing.JLabel HOME;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel MUSIC;
    private javax.swing.JLabel Music;
    private javax.swing.JLabel Personalize;
    private javax.swing.JLabel USER;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
