import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;



import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javazoom.jl.decoder.JavaLayerException;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class Main2 extends javax.swing.JFrame {
Play MC = new Play();
private Timer t;
private ActionListener al;
    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        Music = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Play3 = new javax.swing.JLabel();
        Stop3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Play = new javax.swing.JLabel();
        Stop = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Play2 = new javax.swing.JLabel();
        Stop2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Play1 = new javax.swing.JLabel();
        Stop1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Buy4 = new javax.swing.JButton();
        Buy3 = new javax.swing.JButton();
        Buy2 = new javax.swing.JButton();
        Buy1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Play5 = new javax.swing.JLabel();
        Stop5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Play7 = new javax.swing.JLabel();
        Stop7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Play6 = new javax.swing.JLabel();
        Stop6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Play4 = new javax.swing.JLabel();
        Stop4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Buy6 = new javax.swing.JButton();
        Buy7 = new javax.swing.JButton();
        Buy8 = new javax.swing.JButton();
        Buy5 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        Price2 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        Price4 = new javax.swing.JLabel();
        Price5 = new javax.swing.JLabel();
        Price6 = new javax.swing.JLabel();
        Price7 = new javax.swing.JLabel();
        Price8 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNICO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setForeground(new java.awt.Color(255, 255, 255));
        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Music.png"))); // NOI18N
        Music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Music.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MusicMouseMoved(evt);
            }
        });
        Music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicMouseClicked(evt);
            }
        });
        jPanel6.add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Logout.png"))); // NOI18N
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutMouseMoved(evt);
            }
        });
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel6.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/User.png"))); // NOI18N
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UserMouseMoved(evt);
            }
        });
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        jPanel6.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Home.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
        });
        jPanel6.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 20, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play3MouseMoved(evt);
            }
        });
        Play3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play3MouseReleased(evt);
            }
        });
        jPanel5.add(Play3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop3MouseReleased(evt);
            }
        });
        jPanel5.add(Stop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Stay.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 140, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PlayMouseMoved(evt);
            }
        });
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlayMouseReleased(evt);
            }
        });
        jPanel2.add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StopMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StopMouseReleased(evt);
            }
        });
        jPanel2.add(Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/coldplay.jpg"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 180, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, 140));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play2MouseMoved(evt);
            }
        });
        Play2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play2MouseReleased(evt);
            }
        });
        jPanel4.add(Play2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop2MouseReleased(evt);
            }
        });
        jPanel4.add(Stop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/i hate you.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 140));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 140, 140));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play1MouseMoved(evt);
            }
        });
        Play1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play1MouseReleased(evt);
            }
        });
        jPanel3.add(Play1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop1MouseReleased(evt);
            }
        });
        jPanel3.add(Stop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Sugar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 140, 140));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stay - Zedd, Alessia Cara");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 140, 20));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("A Sky Full of Stars - Coldplay");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 20));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("i hate u, i love u - gnash");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 140, 20));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sugar - Maroon 5");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, 20));

        Buy4.setText("BUY");
        Buy4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy4MouseMoved(evt);
            }
        });
        Buy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy4ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        Buy3.setText("BUY");
        Buy3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy3MouseMoved(evt);
            }
        });
        Buy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy3ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        Buy2.setText("BUY");
        Buy2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy2MouseMoved(evt);
            }
        });
        Buy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy2ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 20));

        Buy1.setText("BUY");
        Buy1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy1MouseMoved(evt);
            }
        });
        Buy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy1ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play5MouseMoved(evt);
            }
        });
        Play5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play5MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play5MouseReleased(evt);
            }
        });
        jPanel8.add(Play5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Stop5MouseMoved(evt);
            }
        });
        Stop5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop5MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop5MouseReleased(evt);
            }
        });
        jPanel8.add(Stop5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Fireworks.png"))); // NOI18N
        jLabel16.setText("jLabel11");
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel16MouseMoved(evt);
            }
        });
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 140));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 140, 140));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play7MouseMoved(evt);
            }
        });
        Play7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play7MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play7MouseReleased(evt);
            }
        });
        jPanel10.add(Play7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Stop7MouseMoved(evt);
            }
        });
        Stop7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop7MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop7MouseReleased(evt);
            }
        });
        jPanel10.add(Stop7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/uptown funk.png"))); // NOI18N
        jLabel18.setText("jLabel11");
        jLabel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel18MouseMoved(evt);
            }
        });
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 140));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 140));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play6MouseMoved(evt);
            }
        });
        Play6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play6MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play6MouseReleased(evt);
            }
        });
        jPanel9.add(Play6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Stop6MouseMoved(evt);
            }
        });
        Stop6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop6MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop6MouseReleased(evt);
            }
        });
        jPanel9.add(Stop6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/SUBEME LA RADIO.png"))); // NOI18N
        jLabel17.setText("jLabel11");
        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel17MouseMoved(evt);
            }
        });
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 150, 160));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 140, 140));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Untitled-3.png"))); // NOI18N
        Play4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Play4MouseMoved(evt);
            }
        });
        Play4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Play4MouseReleased(evt);
            }
        });
        jPanel7.add(Play4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 40, 50));

        Stop4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Stop4MouseMoved(evt);
            }
        });
        Stop4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Stop4MouseReleased(evt);
            }
        });
        jPanel7.add(Stop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/All of me.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 140, 160));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, 140));

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Uptown Funk - Bruno Mars");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 140, 20));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("SUBEME LA RADIO - Enrique Iglesias");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 140, 20));

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Fireworks - Katy Perry");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 140, 20));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("All Of Me - John Legend");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 140, 20));

        Buy6.setText("BUY");
        Buy6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy6MouseMoved(evt);
            }
        });
        Buy6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy6ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        Buy7.setText("BUY");
        Buy7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy7MouseMoved(evt);
            }
        });
        Buy7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy7ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        Buy8.setText("BUY");
        Buy8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy8MouseMoved(evt);
            }
        });
        Buy8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy8ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        Buy5.setText("BUY");
        Buy5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Buy5MouseMoved(evt);
            }
        });
        Buy5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy5ActionPerformed(evt);
            }
        });
        jPanel1.add(Buy5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        jProgressBar1.setForeground(new java.awt.Color(198, 109, 7));
        jProgressBar1.setBorderPainted(false);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 474, 730, 5));

        Price2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price2.setForeground(new java.awt.Color(255, 255, 255));
        Price2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Price2MouseMoved(evt);
            }
        });
        jPanel1.add(Price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 40, 20));

        Price3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 40, 20));

        Price4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 40, 20));

        Price5.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 40, 20));

        Price6.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 40, 20));

        Price7.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 40, 20));

        Price8.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 40, 20));

        Price1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 11)); // NOI18N
        Price1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, 20));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/1498677390_previous.png"))); // NOI18N
        Back.setText("jLabel33");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, 110));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/ede8db99397b584cb6d5d2be3809a3a2.jpg"))); // NOI18N
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackgroundMouseMoved(evt);
            }
        });
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 930, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MusicMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_MusicMouseMoved

    private void MusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_MusicMouseClicked

    private void LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseMoved

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        MC.Stop();
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void UserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_UserMouseMoved

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        // TODO add your handling code here:
        MC.Stop();
        this.setVisible(false);
        new Personalize().setVisible(true);
    }//GEN-LAST:event_UserMouseClicked

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_HomeMouseMoved

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        MC.Stop();
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseEntered

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6MouseMoved

    private void Play3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play3MouseMoved
        // TODO add your handling code here:
        Play3.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play3MouseMoved

    private void Play3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Play3MouseClicked

    private void Play3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play3MouseReleased
    try {
        // TODO add your handling code here:

        MC.Play("G:\\UNICO\\Binaries\\Audio\\Zedd, Alessia Cara - Stay (Lyric Video).mp3");
        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
            jProgressBar1.setValue(0);
            Stop3.setVisible(false);
            Stop3.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
            MC.Stop();
            Play3.setVisible(true);
            }
        };
        t = new Timer(2078,al);
        t.start();

        Stop3.setVisible(true);
        Stop3.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));

        Play3.setVisible(false);
    } catch (JavaLayerException ex) {
        Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_Play3MouseReleased

    private void Stop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop3MouseClicked

    private void Stop3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop3MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop3.setVisible(false);
        Stop3.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play3.setVisible(true);
    }//GEN-LAST:event_Stop3MouseReleased

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        // TODO add your handling code here:
        Play3.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
    }//GEN-LAST:event_jLabel7MouseMoved

    private void PlayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseMoved
        // TODO add your handling code here:
           Play.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_PlayMouseMoved

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_PlayMouseClicked

    private void PlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseReleased

        {
        try // TODO add your handling code here:
        {
            MC.Play("G:\\UNICO\\Binaries\\Audio\\Coldplay - A Sky Full of Stars (Lyrics).mp3");

            al = (ActionEvent ae) -> {
                if (jProgressBar1.getValue() < 100)
                {
                    jProgressBar1.setValue(jProgressBar1.getValue()+1);
                }
                else{t.stop();
                jProgressBar1.setValue(0);
                Stop.setVisible(false);
                Stop.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
                MC.Stop();
                Play.setVisible(true);
                }
            };
            t = new Timer(2615,al);
            t.start();

            Stop.setVisible(true);
            Stop.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));
            
            Play.setVisible(false);
        } catch (JavaLayerException ex) {
            Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_PlayMouseReleased

    private void StopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_StopMouseClicked

    private void StopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopMouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop.setVisible(false);
        Stop.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play.setVisible(true);
    }//GEN-LAST:event_StopMouseReleased

    private void Play2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play2MouseMoved
        // TODO add your handling code here:
        Play2.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play2MouseMoved

    private void Play2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Play2MouseClicked

    private void Play2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play2MouseReleased
    try {
        // TODO add your handling code here:

        MC.Play("G:\\UNICO\\Binaries\\Audio\\gnash - i hate u, i love u ft. olivia o'brien [music video].mp3");
        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
            jProgressBar1.setValue(0);
            Stop2.setVisible(false);
            Stop2.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
            MC.Stop();
            Play2.setVisible(true);
            }
        };
        t = new Timer(2106,al);
        t.start();

        Stop2.setVisible(true);
        Stop2.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));

        Play2.setVisible(false);
    } catch (JavaLayerException ex) {
        Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_Play2MouseReleased

    private void Stop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop2MouseClicked

    private void Stop2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop2MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop2.setVisible(false);
        Stop2.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play2.setVisible(true);
    }//GEN-LAST:event_Stop2MouseReleased

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        // TODO add your handling code here:
        Play2.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
    }//GEN-LAST:event_jLabel5MouseMoved

    private void Play1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play1MouseMoved
        // TODO add your handling code here:
        Play1.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play1MouseMoved

    private void Play1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Play1MouseClicked

    private void Play1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play1MouseReleased
    try {
        // TODO add your handling code here:

        MC.Play("G:\\UNICO\\Binaries\\Audio\\Maroon 5 - Sugar (lyrics).mp3");

        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
            jProgressBar1.setValue(0);
            Stop1.setVisible(false);
            Stop1.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
            MC.Stop();
            Play1.setVisible(true);
            }
        };
        t = new Timer(2198,al);
        t.start();

        Stop1.setVisible(true);
        Stop1.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));

        Play1.setVisible(false);
    } catch (JavaLayerException ex) {
        Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_Play1MouseReleased

    private void Stop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop1MouseClicked

    private void Stop1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop1MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop1.setVisible(false);
        Stop1.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play1.setVisible(true);
    }//GEN-LAST:event_Stop1MouseReleased

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        Play1.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void Buy4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy4MouseMoved
        // TODO add your handling code here:
        Price4.setVisible(true);
        Price4.setText("Rs.40");
    }//GEN-LAST:event_Buy4MouseMoved

    private void Buy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy4ActionPerformed
        // TODO add your handling code here:
         String Song = "Stay - Zedd, Alessia Cara";
        String Price = "Rs.40";
        
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                   
                 }
                             
                               tmp++;
                                                                                   }
                            }
                       
                 }
             catch (Exception e){
                    
                 };
    }//GEN-LAST:event_Buy4ActionPerformed

    private void Buy3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy3MouseMoved
        // TODO add your handling code here:
        Price3.setVisible(true);
        Price3.setText("Rs.40");
    }//GEN-LAST:event_Buy3MouseMoved

    private void Buy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy3ActionPerformed
        // TODO add your handling code here:
        String Song = "i hate u, i love u - gnash";
        String Price = "Rs.40";
         
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                   
                 }
                             
                               tmp++;
                                                                                   }
                            }
                      
                 }
             catch (Exception e){
                   
                 };
    }//GEN-LAST:event_Buy3ActionPerformed

    private void Buy2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy2MouseMoved
        // TODO add your handling code here:
        Price2.setVisible(true);
        Price2.setText("Rs.40");
    }//GEN-LAST:event_Buy2MouseMoved

    private void Buy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy2ActionPerformed
        // TODO add your handling code here:
         String Song = "Sugar - Maroon 5";
        String Price = "Rs.40";
         
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                    
                 }
                             
                               tmp++;
                                                                                   }
                            }
                       
                 }
             catch (Exception e){
                    
                 };
    }//GEN-LAST:event_Buy2ActionPerformed

    private void Buy1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy1MouseMoved
        // TODO add your handling code here:
        Price1.setVisible(true);
        Price1.setText("Rs.40");
    }//GEN-LAST:event_Buy1MouseMoved

    private void Buy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy1ActionPerformed
        // TODO add your handling code here:
         String Song = "A Sky Full of Stars - Coldplay";
        String Price = "Rs.40";
         
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                   
                 }
                             
                               tmp++;
                                                                                   }
                            }
                       
                 }
             catch (Exception e){
                    
                 };
    }//GEN-LAST:event_Buy1ActionPerformed

    private void Play5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play5MouseMoved
        // TODO add your handling code here:
        Play5.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play5MouseMoved

    private void Play5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Play5MouseClicked

    private void Play5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play5MouseReleased
        // TODO add your handling code here:

        {   try {
            MC.Play("G:\\UNICO\\Binaries\\Audio\\Katy Perry - Firework (Official).mp3");
            } catch (JavaLayerException ex) {
                Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
            }
}

        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
                jProgressBar1.setValue(0);
                Stop5.setVisible(false);
                Stop5.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
                MC.Stop();
                Play5.setVisible(true);
            }
        };
        t = new Timer(2204,al);
        t.start();

        Stop5.setVisible(true);
        Stop5.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\stop-1.png"));

        Play5.setVisible(false);
    }//GEN-LAST:event_Play5MouseReleased

    private void Stop5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop5MouseMoved

    private void Stop5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop5MouseClicked

    private void Stop5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop5MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop5.setVisible(false);
        Stop5.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play5.setVisible(true);
    }//GEN-LAST:event_Stop5MouseReleased

    private void jLabel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseMoved
        // TODO add your handling code here:
        Play5.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
    }//GEN-LAST:event_jLabel16MouseMoved

    private void Play7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play7MouseMoved
        // TODO add your handling code here:
        Play7.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play7MouseMoved

    private void Play7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Play7MouseClicked

    private void Play7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play7MouseReleased
        // TODO add your handling code here:

        {   try {
            MC.Play("G:\\UNICO\\Binaries\\Audio\\Mark Ronson - Uptown Funk ft. Bruno Mars.mp3");
            } catch (JavaLayerException ex) {
                Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
            }
}
        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
                jProgressBar1.setValue(0);
                Stop7.setVisible(false);
                Stop7.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
                MC.Stop();
                Play7.setVisible(true);
            }
        };
        t = new Timer(2646,al);
        t.start();

        Stop7.setVisible(true);
        Stop7.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\stop-1.png"));

        Play7.setVisible(false);
    }//GEN-LAST:event_Play7MouseReleased

    private void Stop7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop7MouseMoved

    private void Stop7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop7MouseClicked

    private void Stop7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop7MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop7.setVisible(false);
        Stop7.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play7.setVisible(true);
    }//GEN-LAST:event_Stop7MouseReleased

    private void jLabel18MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseMoved
        // TODO add your handling code here:
        Play7.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));

    }//GEN-LAST:event_jLabel18MouseMoved

    private void Play6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play6MouseMoved
        // TODO add your handling code here:
        Play6.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play6MouseMoved

    private void Play6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Play6MouseClicked

    private void Play6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play6MouseReleased
        // TODO add your handling code here:

        {   try {
            MC.Play("G:\\UNICO\\Binaries\\Audio\\Enrique Iglesias - SUBEME LA RADIO (Official Video) ft. Descemer Bueno, Zion.mp3");
            } catch (JavaLayerException ex) {
                Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
            }
}
        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
                jProgressBar1.setValue(0);
                Stop6.setVisible(false);
                Stop6.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
                MC.Stop();
                Play6.setVisible(true);
            }
        };
        t = new Timer(2188,al);
        t.start();

        Stop6.setVisible(true);
        Stop6.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));

        Play6.setVisible(false);
    }//GEN-LAST:event_Play6MouseReleased

    private void Stop6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop6MouseMoved

    private void Stop6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop6MouseClicked

    private void Stop6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop6MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop6.setVisible(false);
        Stop6.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play6.setVisible(true);
    }//GEN-LAST:event_Stop6MouseReleased

    private void jLabel17MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseMoved
        // TODO add your handling code here:
        Play6.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));

    }//GEN-LAST:event_jLabel17MouseMoved

    private void Play4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play4MouseMoved
        // TODO add your handling code here:
        Play4.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play2-1.png"));
    }//GEN-LAST:event_Play4MouseMoved

    private void Play4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Play4MouseClicked

    private void Play4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play4MouseReleased
    try {
        // TODO add your handling code here:

        MC.Play("G:\\UNICO\\Binaries\\Audio\\John Legend   All Of Me Lyrics.mp3");
        al = (ActionEvent ae) -> {
            if (jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else{t.stop();
            jProgressBar1.setValue(0);
            Stop4.setVisible(false);
            Stop4.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
            MC.Stop();
            Play4.setVisible(true);
            }
        };
        t = new Timer(2680,al);
        t.start();
        
        { 
            Stop4.setVisible(true);
            Stop4.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));
            
            Play4.setVisible(false);}
    } catch (JavaLayerException ex) {
        Logger.getLogger(Main2.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_Play4MouseReleased

    private void Stop4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop4MouseMoved

    private void Stop4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop4MouseClicked

    private void Stop4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop4MouseReleased
        // TODO add your handling code here:
        MC.Stop();
        Stop4.setVisible(false);
        Stop4.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\stop-1.png"));
        jProgressBar1.setValue(0);
        t.stop();
        Play4.setVisible(true);
    }//GEN-LAST:event_Stop4MouseReleased

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        // TODO add your handling code here:
        Play4.setIcon(new ImageIcon("G:\\UNICO\\src\\Background\\Play.png"));
    }//GEN-LAST:event_jLabel11MouseMoved

    private void Buy6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy6MouseMoved
        // TODO add your handling code here:
        Price6.setVisible(true);
        Price6.setText("Rs.40");
    }//GEN-LAST:event_Buy6MouseMoved

    private void Buy6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy6ActionPerformed
        // TODO add your handling code here:
         String Song = "Fireworks - Katy Perry";
        String Price = "Rs.40";
         
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                   
                 }
                             
                               tmp++;
                                                                                   }
                            }
                       
                 }
             catch (Exception e){
                    
                 };

    }//GEN-LAST:event_Buy6ActionPerformed

    private void Buy7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy7ActionPerformed
        // TODO add your handling code here:
         String Song = "SUBEME LA RADIO - Enrique Iglesias";
        String Price = "Rs.40";
         
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                    
                 }
                             
                               tmp++;
                                                                                   }
                            }
                     
                 }
             catch (Exception e){
                   
                 };
    }//GEN-LAST:event_Buy7ActionPerformed

    private void Buy8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy8ActionPerformed
        // TODO add your handling code here:
        String Song = "Uptown Funk - Bruno Mars";
        String Price = "Rs.40";
         
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                   
                 }
                             
                               tmp++;
                                                                                   }
                            }
                       
                 }
             catch (Exception e){
                    
                 };
    }//GEN-LAST:event_Buy8ActionPerformed

    private void Buy5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy5MouseMoved
        // TODO add your handling code here:
        Price5.setVisible(true);
        Price5.setText("Rs.40");
    }//GEN-LAST:event_Buy5MouseMoved

    private void Buy5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy5ActionPerformed
        // TODO add your handling code here:
         String Song = "All Of Me - John Legend";
        String Price = "Rs.40";
        
        String sql="Select * from signup;";
        
             try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               String Pwd=rs.getString("Password");
                               if ((Login.Uname.equals(User)) && (Login.Pass.equals(Pwd))) {
                                try {
                                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con1.createStatement();
                     String qu = "Insert into Buy values ('"+Login.Uname+"','"+Song+"','"+Price+"',Curdate());";
            st.executeUpdate(qu);
             JOptionPane.showMessageDialog(this, "Your Order has been placed Successfully"+"\n"+"it will be delivered in 4-5 buisiness days");
            JOptionPane.showMessageDialog(null , "Thanks for Purchasing"); 
                                }
                                catch (Exception e){
                  
                 }
                             
                               tmp++;
                                                                                   }
                            }
                      
                 }
             catch (Exception e){
                   
                 };
    }//GEN-LAST:event_Buy5ActionPerformed

    private void Price2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Price2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Price2MouseMoved

    private void BackgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseMoved
        // TODO add your handling code here:
        Play.setIcon(new ImageIcon("E:\\UNICO\\src\\Background\\Play.png"));
        Price2.setText("");
        Price2.setVisible(false);
        Price3.setText("");
        Price3.setVisible(false);
        Price4.setText("");
        Price4.setVisible(false);
        Price5.setText("");
        Price5.setVisible(false);
        Price6.setText("");
        Price6.setVisible(false);
        Price7.setText("");
        Price7.setVisible(false);
        Price8.setText("");
        Price8.setVisible(false);
        Price1.setText("");
        Price1.setVisible(false);
    }//GEN-LAST:event_BackgroundMouseMoved

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
        MC.Stop();
    }//GEN-LAST:event_BackMouseClicked

    private void Buy7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy7MouseMoved
        // TODO add your handling code here:
        Price7.setVisible(true);
        Price7.setText("Rs.40");
    }//GEN-LAST:event_Buy7MouseMoved

    private void Buy8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy8MouseMoved
        // TODO add your handling code here:
        Price8.setVisible(true);
        Price8.setText("Rs.40");
    }//GEN-LAST:event_Buy8MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Buy1;
    private javax.swing.JButton Buy2;
    private javax.swing.JButton Buy3;
    private javax.swing.JButton Buy4;
    private javax.swing.JButton Buy5;
    private javax.swing.JButton Buy6;
    private javax.swing.JButton Buy7;
    private javax.swing.JButton Buy8;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Music;
    public javax.swing.JLabel Play;
    public javax.swing.JLabel Play1;
    public javax.swing.JLabel Play2;
    public javax.swing.JLabel Play3;
    public javax.swing.JLabel Play4;
    public javax.swing.JLabel Play5;
    public javax.swing.JLabel Play6;
    public javax.swing.JLabel Play7;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Price4;
    private javax.swing.JLabel Price5;
    private javax.swing.JLabel Price6;
    private javax.swing.JLabel Price7;
    private javax.swing.JLabel Price8;
    public javax.swing.JLabel Stop;
    public javax.swing.JLabel Stop1;
    public javax.swing.JLabel Stop2;
    public javax.swing.JLabel Stop3;
    public javax.swing.JLabel Stop4;
    public javax.swing.JLabel Stop5;
    public javax.swing.JLabel Stop6;
    public javax.swing.JLabel Stop7;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
