
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class Modify extends javax.swing.JFrame {

    /**
     * Creates new form Modify
     */
    public Modify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Music = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Opassword = new javax.swing.JPasswordField();
        Npassword = new javax.swing.JPasswordField();
        Apply = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNICO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Music.png"))); // NOI18N
        Music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Music.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MusicMouseMoved(evt);
            }
        });
        Music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicMouseClicked(evt);
            }
        });
        jPanel1.add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Logout.png"))); // NOI18N
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutMouseMoved(evt);
            }
        });
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/User.png"))); // NOI18N
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UserMouseMoved(evt);
            }
        });
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Home.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Old Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 180, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("New Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 300, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 300, 10));

        Opassword.setBackground(new java.awt.Color(0, 0, 0));
        Opassword.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Opassword.setForeground(new java.awt.Color(255, 255, 255));
        Opassword.setBorder(null);
        jPanel2.add(Opassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 260, 30));

        Npassword.setBackground(new java.awt.Color(0, 0, 0));
        Npassword.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Npassword.setForeground(new java.awt.Color(255, 255, 255));
        Npassword.setBorder(null);
        jPanel2.add(Npassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 260, 30));

        Apply.setBackground(new java.awt.Color(0, 0, 0));
        Apply.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Apply.setForeground(new java.awt.Color(255, 255, 255));
        Apply.setText("Apply");
        Apply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });
        jPanel2.add(Apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 140, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 190, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 300, 20));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 260, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Background.jpg"))); // NOI18N
        Background.setText("jLabel1");
        jPanel2.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -200, 790, 1000));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 760, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MusicMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_MusicMouseMoved

    private void LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_LogoutMouseMoved

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void UserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_UserMouseMoved

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Personalize().setVisible(true);
    }//GEN-LAST:event_UserMouseClicked

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_HomeMouseMoved

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseEntered

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseMoved

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        // TODO add your handling code here:
        int c = JOptionPane.showConfirmDialog(this, "Do you want to Change","Confirm",JOptionPane.YES_NO_OPTION);
        if (c==0) {
           
            
            String Opass = Opassword.getText();
            String Npass = Npassword.getText();
            String sql = "Select * from Signup;";
            try {
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st;
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                st = con1.createStatement();
                 ResultSet rs = st.executeQuery(sql);
                 int tmp=0;
                   while(rs.next())
                                   {
                               String Pwd=rs.getString("Password");
                               String Uname=rs.getString("Username");
                               if((Opass.equals(Pwd)) && (Login.Uname.equals(Uname)) ) {
                                tmp++;
                                   try {
                                       Class.forName("java.sql.DriverManager");
                                          Connection con2;
                                            Statement st1;
                                              con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                                            st1 = con1.createStatement();
                                            String qu = "Update Signup set Password = '"+Npass+"' where Username = '"+Uname+"';";
                                            st1.executeUpdate(qu);
                                            JOptionPane.showMessageDialog(this,"Your Password has been changed");
                                        }
                                   catch (Exception e){
                                       
                                   }
                                   
                                     }
                               
                            }
                   
                                   
                
                
                
            }
            catch ( Exception e) {
                                           
                                           
                                           }
        }
        username.setText("");
        Opassword.setText("");
        Npassword.setText("");
    }//GEN-LAST:event_ApplyActionPerformed

    private void MusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_MusicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Music;
    private javax.swing.JPasswordField Npassword;
    private javax.swing.JPasswordField Opassword;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
