import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class Personalize extends javax.swing.JFrame {

    /**
     * Creates new form Personalize
     */
    public Personalize() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Music = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        uname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        Modify = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        UserINFO = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        MODIFY = new javax.swing.JLabel();
        DEACTIVATE = new javax.swing.JLabel();
        INFO = new javax.swing.JLabel();
        Bought = new javax.swing.JLabel();
        BOUGHT = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNICO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Music.png"))); // NOI18N
        Music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Music.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MusicMouseMoved(evt);
            }
        });
        Music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicMouseClicked(evt);
            }
        });
        jPanel1.add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 40));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Logout.png"))); // NOI18N
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutMouseMoved(evt);
            }
        });
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/User.png"))); // NOI18N
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UserMouseMoved(evt);
            }
        });
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Home.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 600));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 40));

        fname.setBackground(new java.awt.Color(0, 0, 0));
        fname.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(null);
        fname.setEnabled(false);
        fname.setOpaque(false);
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 370, 40));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Last Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 40));

        lname.setBackground(new java.awt.Color(0, 0, 0));
        lname.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setBorder(null);
        lname.setEnabled(false);
        lname.setOpaque(false);
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 370, 40));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 370, 20));

        uname.setBackground(new java.awt.Color(0, 0, 0));
        uname.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setBorder(null);
        uname.setEnabled(false);
        uname.setOpaque(false);
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 370, 40));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email-ID");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 40));

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.setEnabled(false);
        email.setOpaque(false);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 370, 40));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("City");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 160, 40));

        address.setBackground(new java.awt.Color(0, 0, 0));
        address.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(null);
        address.setEnabled(false);
        address.setOpaque(false);
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 370, 40));

        city.setBackground(new java.awt.Color(0, 0, 0));
        city.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setBorder(null);
        city.setEnabled(false);
        city.setOpaque(false);
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 370, 40));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Pin-Code");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 40));

        pin.setBackground(new java.awt.Color(0, 0, 0));
        pin.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        pin.setForeground(new java.awt.Color(255, 255, 255));
        pin.setBorder(null);
        pin.setEnabled(false);
        pin.setOpaque(false);
        jPanel2.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 370, 40));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 370, 10));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 370, 10));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 370, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 370, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 370, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 370, 10));

        Modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/pen-checkbox-128.png"))); // NOI18N
        Modify.setText("jLabel9");
        Modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modify.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ModifyMouseMoved(evt);
            }
        });
        Modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModifyMouseEntered(evt);
            }
        });
        jPanel2.add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, 100));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/ic_delete_48px-128.png"))); // NOI18N
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DeleteMouseMoved(evt);
            }
        });
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 140, 110));

        UserINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/1494907775_icons_user.png"))); // NOI18N
        UserINFO.setText("jLabel7");
        UserINFO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserINFO.setPreferredSize(new java.awt.Dimension(128, 128));
        UserINFO.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UserINFOMouseMoved(evt);
            }
        });
        UserINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserINFOMouseClicked(evt);
            }
        });
        jPanel2.add(UserINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, 120));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Address ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, 40));

        MODIFY.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        MODIFY.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(MODIFY, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 120, 20));

        DEACTIVATE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        DEACTIVATE.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(DEACTIVATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 70, 20));

        INFO.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        INFO.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 90, 20));

        Bought.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/if_shopping-cart_1608412.png"))); // NOI18N
        Bought.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bought.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BoughtMouseMoved(evt);
            }
        });
        Bought.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoughtMouseClicked(evt);
            }
        });
        jPanel2.add(Bought, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        BOUGHT.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        BOUGHT.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(BOUGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 100, 20));

        Background.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/ede8db99397b584cb6d5d2be3809a3a2.jpg"))); // NOI18N
        Background.setText("jLabel1");
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackgroundMouseMoved(evt);
            }
        });
        jPanel2.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, -160, 1170, 1000));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 760, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MusicMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_MusicMouseMoved

    private void MusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_MusicMouseClicked

    private void LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_LogoutMouseMoved

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void UserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_UserMouseMoved

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Personalize().setVisible(true);
    }//GEN-LAST:event_UserMouseClicked

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_HomeMouseMoved

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseEntered

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseMoved

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Modify().setVisible(true);
    }//GEN-LAST:event_ModifyMouseClicked

    private void ModifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyMouseEntered

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
       
        String sql = "Select * from Signup;";
       
       
         {
            try {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
            st = con1.createStatement();
            ResultSet rs = st.executeQuery(sql);
            int tmp=0;
            while(rs.next())
            {
                String Pwd=rs.getString("Password");
                String Uname=rs.getString("Username");
                if((Login.Pass.equals(Pwd)) && (Login.Uname.equals(Uname))) {
                    tmp++;
                    try {
                        Class.forName("java.sql.DriverManager");
                        Connection con2;
                        Statement st1;
                        con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                        st1 = con1.createStatement();
                        String qu = "delete from Signup where Username = '"+Login.Uname+"';";
                        st.executeUpdate(qu);
                        JOptionPane.showMessageDialog(null , "Your account has been deactivated");
                        this.setVisible(false);
                        new Login().setVisible(true);
                    }
                    catch (Exception e){
                       
                    }
                  

                }

            }
            if (tmp==0)
            {
                JOptionPane.showMessageDialog(null, "User does not exist");
            }

        }
        catch ( Exception e) {
            

        }
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void UserINFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserINFOMouseClicked
        // TODO add your handling code here:
         
          //String Pass = JOptionPane.showInputDialog(this,"Enter Your Password");
        String Fname = " ";
        String Lname = " ";
        String Username = " ";
        String Email = " ";
        String Address = " ";
        String City = " ";
        String Pin = " ";
        String sql = "Select * from Signup;";
            try {
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st;
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                st = con1.createStatement();
                 ResultSet rs = st.executeQuery(sql);
                 int tmp=0;
                   while(rs.next())
                                   {
                              String Pwd=rs.getString("Password");
                               String Uname=rs.getString("Username");
                               if((Login.Pass.equals(Pwd)) && (Login.Uname.equals(Uname)) ) {
                                tmp++;
                                   try {
                                       Class.forName("java.sql.DriverManager");
                                          Connection con2;
                                            Statement st1;
                                              con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                                            st1 = con1.createStatement();
                                            String qu = "select * from signup where Username = '"+Login.Uname+"';";
                                            ResultSet rs1;
                                            rs1 = st1.executeQuery(qu);
                                            while(rs1.next()){
                                                Fname = rs1.getString(1);
                Lname = rs1.getString(2);
                Username = rs1.getString(3);
                Email = rs1.getString(4);
                Address = rs1.getString(6);
                City = rs1.getString(7);
                Pin = rs1.getString(8);
                                            }
                                            fname.setText("" + Fname);
            lname.setText("" + Lname);
            uname.setText("" + Username);
            email.setText("" + Email);
            address.setText("" + Address);
            city.setText("" + City);
            pin.setText("" + Pin);
                                            
                                            
                                            
                                        }
                                   catch (Exception e){
                                      
                                   }
                                   
                                     }
                               
                            }
                  
                
                
                
            }
            catch ( Exception e) {
                                           
                                           
                                           }
                   
    }//GEN-LAST:event_UserINFOMouseClicked

    private void ModifyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseMoved
        // TODO add your handling code here:
        MODIFY.setText("Change Password");
    }//GEN-LAST:event_ModifyMouseMoved

    private void DeleteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseMoved
        // TODO add your handling code here:
        DEACTIVATE.setText("Deactivate");
    }//GEN-LAST:event_DeleteMouseMoved

    private void UserINFOMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserINFOMouseMoved
        // TODO add your handling code here:
        INFO.setText("Personal Info");
    }//GEN-LAST:event_UserINFOMouseMoved

    private void BackgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseMoved
        // TODO add your handling code here:
         MODIFY.setText("");
         DEACTIVATE.setText("");
         INFO.setText("");
          BOUGHT.setText("");
    }//GEN-LAST:event_BackgroundMouseMoved

    private void BoughtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoughtMouseMoved
        // TODO add your handling code here:
        BOUGHT.setText("Your Orders");
    }//GEN-LAST:event_BoughtMouseMoved

    private void BoughtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoughtMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Bought().setVisible(true);
    }//GEN-LAST:event_BoughtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BOUGHT;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Bought;
    private javax.swing.JLabel DEACTIVATE;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel INFO;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel MODIFY;
    private javax.swing.JLabel Modify;
    private javax.swing.JLabel Music;
    private javax.swing.JLabel User;
    private javax.swing.JLabel UserINFO;
    private javax.swing.JTextField address;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
