
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class Sign_Up extends javax.swing.JFrame {

   
    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() {
        initComponents();
       
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Member = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        Create = new javax.swing.JButton();
        Agree = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        address = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        pin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        city = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNICO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 110, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 110, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 110, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email-ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 110, 40));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("City");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 160, 40));

        fname.setBackground(new java.awt.Color(0, 0, 0));
        fname.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(null);
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 330, 40));

        lname.setBackground(new java.awt.Color(0, 0, 0));
        lname.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setBorder(null);
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 330, 40));

        uname.setBackground(new java.awt.Color(0, 0, 0));
        uname.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setBorder(null);
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 330, 40));

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 330, 40));

        Member.setBackground(new java.awt.Color(0, 0, 0));
        Member.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        Member.setForeground(new java.awt.Color(255, 0, 0));
        Member.setText("Already a Member");
        Member.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberMouseClicked(evt);
            }
        });
        getContentPane().add(Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 120, 20));

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 330, 40));

        Create.setBackground(new java.awt.Color(0, 0, 0));
        Create.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Create Account");
        Create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 160, 30));

        Agree.setBackground(new java.awt.Color(0, 0, 0));
        Agree.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        Agree.setForeground(new java.awt.Color(255, 255, 255));
        Agree.setText("I Agree to all Terms & Conditions");
        Agree.setBorder(null);
        Agree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agree.setOpaque(false);
        getContentPane().add(Agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 230, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 330, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 330, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 330, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 330, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 110, 10));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 110, 40));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 330, 10));

        address.setBackground(new java.awt.Color(0, 0, 0));
        address.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(null);
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 330, 40));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 330, 10));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 330, 10));

        pin.setBackground(new java.awt.Color(0, 0, 0));
        pin.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        pin.setForeground(new java.awt.Color(255, 255, 255));
        pin.setBorder(null);
        getContentPane().add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 330, 40));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pin-Code");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 110, 40));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 330, 10));

        city.setBackground(new java.awt.Color(0, 0, 0));
        city.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setBorder(null);
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 330, 40));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 160, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Background.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 820, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void MemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
    new Login().setVisible(true);
    }//GEN-LAST:event_MemberMouseClicked

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here
        
        String Fname = fname.getText();
        String Lname = lname.getText();
        String Uname = uname.getText();
        String Email = email.getText();
        String Pass  = password.getText();
        String Address = address.getText(); 
        String City = city.getText();
        String Pin = pin.getText();
           String sql="Select * from signup;";        
        {if (Agree.isSelected()==true)
            
            if ((Fname.length()==0) ||
                (Lname.length()==0) ||
                (Uname.length()==0) ||
                (Email.length()==0) ||
                (Pass.length()==0) ||
                (Address.length()==0) ||
                 (City.length()==0) ||
                (Pin.length()==0))
                JOptionPane.showMessageDialog(this,"Please fill all the neccessary details"+"\n"+"Try again");
        
        else {
          try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st=con.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                       int tmp=0;
                       while(rs.next()) 
                            {
                               String User=rs.getString("Username");
                               if ((Uname.equals(User)))
                               {
                                   JOptionPane.showMessageDialog(this,"Username already exists");
                                   tmp++;
                               }
                            }
                       if (tmp==0){
                           
                       try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Unico","root","admin");
                    Statement st1=con.createStatement();
               String qu = "Insert into signup values ('"+Fname+"','"+Lname+"','"+Uname+"','"+Email+"','"+Pass+"','"+Address+"','"+City+"','"+Pin+"');";
            st.executeUpdate(qu);
           JOptionPane.showMessageDialog(this,"Your Account has been Successfully Created");
                              {this.setVisible(false);
    new Login().setVisible(true);}
             }
                        catch (Exception e)
    {
         JOptionPane.showMessageDialog(this,e);
    } 
    
                       }
          }
    catch (Exception e)
    {
         JOptionPane.showMessageDialog(this,e);
    }
           
           }
           else if (Agree.isSelected()==false)
                   {
                       JOptionPane.showMessageDialog(this,"You have not Agreed our Terms & Conditions");
                   }
        
        }
        
    }//GEN-LAST:event_CreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Agree;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Create;
    private javax.swing.JLabel Member;
    private javax.swing.JTextField address;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible() {
        }
    }
}
